### ISSUE TITLE
PlotSquared restriction direction bug 

### ISSUE THREAD

**Issue by Hdadaw** [boy0001/FastAsyncWorldedit#1334] opened 2019-09-29 12:34 UTC
**Debug paste link**:
https://athion.net/ISPaster/paste/view/1851055e534e40fe918f0027388b6f95

**Description of the problem:**
Any player **without //wea or any bypass permissions** (this bug was found by players on my public server) can do any WorldEdit operation, for example **//set* outside merged plot in directions **South-West** and **North-East**.
Video with a detailed demonstration: https://youtu.be/iematG2mBvk

**How to replicate**:
Claim and merge plots like demonstrated on video or like this
![image](https://user-images.githubusercontent.com/32250813/65832509-4d1c2380-e2f7-11e9-87e8-ea5657c6a304.png)
and try **//set**, taking the points inside your plot so that inside the selection there is a territory outside your plot diagonally in the directions **South-West** or **North-East**, like showed on video: https://youtu.be/iematG2mBvk

**Checklist**:

- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Hdadaw** [comment] 2020-01-25 14:30
any update?

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:16
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:16 UTC
