### ISSUE TITLE
Error when doing /up

### ISSUE THREAD

**Issue by UltraX3** [boy0001/FastAsyncWorldedit#22] opened 2016-04-08 00:28 UTC
```Java
[20:18:15 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:253) [FastAsyncWorldEdit.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalStateException: Asynchronous block remove!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at net.minecraft.server.v1_8_R3.Block.remove(Block.java:317) ~[spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at net.minecraft.server.v1_8_R3.Chunk.a(Chunk.java:585) ~[spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at net.minecraft.server.v1_8_R3.World.setTypeAndData(World.java:396) ~[spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.setTypeIdAndData(CraftBlock.java:137) ~[spigot.jar:git-PaperSpigot-60136e7-18fbb24]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3.setBlock(Spigot_v1_8_R3.java:237) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:416) ~[?:?]
        at com.sk89q.worldedit.world.AbstractWorld.setBlock(AbstractWorld.java:83) ~[?:?]
        at com.sk89q.worldedit.world.AbstractWorld.setBlockType(AbstractWorld.java:58) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.floatAt(AbstractPlayerActor.java:304) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.ascendUpwards(AbstractPlayerActor.java:292) ~[?:?]
        at com.sk89q.worldedit.command.NavigationCommands.up(NavigationCommands.java:181) ~[?:?]
        ... 12 more
```

**Comment by Quicksteve** [comment] 2016-04-14 10:47
Duplicate of #27, which was fixed?

**Closed** 2016-04-14 12:47 UTC
