### ISSUE TITLE
Error with restoring snapshots

### ISSUE THREAD

**Issue by bloggy** [boy0001/FastAsyncWorldedit#1301] opened 2019-05-17 07:01 UTC
**Spigot / Paper version:**
This server is running Paper version git-Paper-617 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**FAWE Version (using latest dev build as of 17th May 2019):**
https://i.imgur.com/4DXc4jb.png
Also tested with the download version from here:
https://empcraft.com/fawe/download/?bukkit113

First I get this error everytime I start my server:
https://hastebin.com/gosiropoxu.sql

Second I setup snapshots correctly and they work (tested!) with default WorldEdit (WorldEdit v7.0.0-beta-05;6bbf29b) but not with FAWE. 

**How to reproduce:**
I select a chunk ingame with //pos1 and //pos2 and then //chunk -s
and then I type //restore
then this happens:
https://i.imgur.com/ET2cKkj.png

Snapshots configuration in legacy config is correct:
snapshots:
    directory: worldbackup

Inside that worldbackup folder is a folder called "Lyria" which contains a 1:1 copy of the world on the server.

The world has been generated with WorldPainter and is a fully functional 1.13.2 world.
The same issue occurs with a default minecraft world (just tested).

**Comment by bloggy** [comment] 2019-05-23 19:48
Does anybody else have this issue? Restoring is pretty important for us, would be great if somebody could check this

**Comment by TheoRetisch1** [comment] 2019-06-02 10:19
I have the same problem with the latest FAWE version 1.13-117.

**Comment by RedstoneFuture** [comment] 2019-10-02 19:58
I can reproduce this issue.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:15
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:15 UTC

**Comment by bloggy** [comment] 2020-09-01 11:37
btw. restoring still not working in latest dev build "Loading FastAsyncWorldEdit v1.16.2"

https://i.imgur.com/Ib1VL77.png
