### ISSUE TITLE
//smooth 50 -s produces Out of Bounds error

### ISSUE THREAD

**Issue by Tobberz** [boy0001/FastAsyncWorldedit#1276] opened 2019-02-27 17:34 UTC
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**:
https://incendo.org/paste/view/da0c002b7dc34411b68baf8d3601d8b1

**Description of the problem:**
Error:
https://pastebin.com/cEMVEvU0

Identical issue, resolved April 18
https://github.com/boy0001/FastAsyncWorldedit/issues/985

**How to replicate**:
//smooth 50 -s doesn't work on large region selecitons. Works fine on small region selections.

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:13
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:13 UTC
