### ISSUE TITLE
Unable change block after give the limit name

### ISSUE THREAD

**Issue by chnigel** [boy0001/FastAsyncWorldedit#1326] opened 2019-08-17 18:47 UTC
**Debug paste link**:
https://athion.net/ISPaster/paste/view/25970daa4a1e4a6eb22af39d8600ef09

**Description of the problem:**
Hello, Developer, I use FastAsyncWorldEdit in myserver and fawe version is [sponge112-19.07.25].After I added node "fawe.limit.<named>" , modified the config and use command like "//stack" or "//set", it says "No allowed region", but if I give fawe.* permission, then everything goes right

**How to replicate**:
just clear all permission then give the limit name

**Checklist**:

- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:16
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:16 UTC
