### ISSUE TITLE
COMPRESSION BINDING NOT FOUND

### ISSUE THREAD

**Issue by Reeferx7** [boy0001/FastAsyncWorldedit#378] opened 2016-12-28 17:09 UTC
With /fawe debugpaste i get this error:

http://pastebin.com/T2VB43Ec

About my problem i get this this on server startup:

http://pastebin.com/7UJuik6b

Server version 1.8
Java 8

Config:
http://pastebin.com/0rb6Wk46

**Comment by boy0001** [comment] 2017-01-02 20:53
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/372

**Closed by boy0001** 2017-01-02 20:53 UTC
Labels: [✖] Duplicate, [✖] Wont Fix
