### ISSUE TITLE
FAWE a.a5.2 bugs founded

### ISSUE THREAD

**Issue by Selva6498** [boy0001/FastAsyncWorldedit#1374] opened 2020-05-06 11:02 UTC
while using the latest version of fawe i found this:
-/br sphere (any pattern) **1** doesn't produce anything. instead from size 2 and above it workes correctly. verify others type of brushes if at size 1 or 2 makes issues.
-numerical id's with /v are not recognized, instead in the original versions of voxels it was available
-while ID-library plugin is installed, both FAWE and FAVS don't work with numerical id's from newer versions of minecraft.
-missing commands:
     //transform
     /setskylight
     /br copypaste
     /loadbrush
-when i select and copy a region, if i accidentally select another region i can't paste the previous one no more; i need to select it again.

if i find more bugs i will report to you so you can fix them :)

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:19
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:19 UTC
