### ISSUE TITLE
com.sk89q.worldguard.LocalPlayer, but class was expected

### ISSUE THREAD

**Issue by Blitheness** [boy0001/FastAsyncWorldedit#1232] opened 2018-12-19 17:01 UTC
# Bug report / plea for help
**Debug paste link**:
https://hastebin.com/diquwibuza

**Description of the problem:**
Non-admin/op player tries to execute a worldedit command that they have permission to use (via Luckperms).

> [11:50:02 INFO]: XXX issued server command: //drain 20
> [11:50:02 WARN]: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.LocalPlayer, but class was expected
> [11:50:02 WARN]:        at com.boydti.fawe.bukkit.regions.Worldguard.isAllowed(Worldguard.java:74)
> [11:50:02 WARN]:        at com.boydti.fawe.bukkit.regions.Worldguard.getRegion(Worldguard.java:61)
> [11:50:02 WARN]:        at com.boydti.fawe.bukkit.regions.Worldguard.getMask(Worldguard.java:98)
> [11:50:02 WARN]:        at com.boydti.fawe.util.WEManager.getMask(WEManager.java:136)
> [11:50:02 WARN]:        at com.boydti.fawe.util.WEManager.getMask(WEManager.java:72)
> [11:50:02 WARN]:        at com.boydti.fawe.object.FawePlayer.getCurrentRegions(FawePlayer.java:548)
> [11:50:02 WARN]:        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:316)
> [11:50:02 WARN]:        at com.boydti.fawe.util.EditSessionBuilder.build(EditSessionBuilder.java:194)
> [11:50:02 WARN]:        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1282)
> [11:50:02 WARN]:        at com.sk89q.worldedit.internal.command.WorldEditBinding.getEditSession(WorldEditBinding.java:109)
> [11:50:02 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [11:50:02 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [11:50:02 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [11:50:02 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
> [11:50:02 WARN]:        at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:170)
> [11:50:02 WARN]:        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:241)
> [11:50:02 WARN]:        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133)
> [11:50:02 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414)
> [11:50:02 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437)
> [11:50:02 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418)
> [11:50:02 WARN]:        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536)
> [11:50:02 WARN]:        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328)
> [11:50:02 WARN]:        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25)
> [11:50:02 WARN]:        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15)
> [11:50:02 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
> [11:50:02 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
> [11:50:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [11:50:02 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [11:50:02 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [11:50:02 WARN]:        at java.lang.Thread.run(Thread.java:748)

**How to replicate**:
Non-op player with permission for //drain (or //repl, etc) attempts to use the command, nothing happens. Exception in console.

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [?] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:12
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:12 UTC
