### ISSUE TITLE
NPE in BukkitQueue_1_12.setBlockLight

### ISSUE THREAD

**Issue by NachtRaben** [boy0001/FastAsyncWorldedit#1266] opened 2019-02-07 02:12 UTC
# Bug report for FastAsyncWorldEdit <1.12.2
**Debug paste link**:
https://hastebin.com/ogexilubet
Updated Link: https://paste.gg/p/anonymous/380f39f0e5ff4ce19ebd0d64db4dfc87

**Description of the problem:**
We believe there is a null pointer during chunk section relighting, could be related to the API being used.
We use AsyncWorld in several spots of our code, but can't trace it back to our code from the logs.

the chunk sections for setBlockLight, getOpacity, and getLightEmitted in BukkitQueue_1_12.java are randomly null and cause NPE's to be thrown. If I go to affected regions that cause this to spam console and select a region and do //removelight //fixlight the errors go away. I feel this is due to some kind of light info corruption, but I don't know why the chunk sections are null when you specifically do a null check in NMSMappedFaweQueue and MappedFaweQueue

**How to replicate**:

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:13
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:13 UTC
