### ISSUE TITLE
[API BUG] Patterns added with WorldEdit API are not working 

### ISSUE THREAD

**Issue by LoneDev6** [boy0001/FastAsyncWorldedit#1337] opened 2019-10-18 12:07 UTC
**Debug paste link**:
https://athion.net/ISPaster/paste/view/9d55fbed4440474d8dfcb4e958462fb7

**Description of the problem:**
Seems that FAWE is not loading patterns added with WorldEdit API:
![image](https://user-images.githubusercontent.com/27242001/67092798-77535980-f1b0-11e9-9ca2-12b1259f0847.png)

I don't see it in autocomplete and they are not working ingame. They are working fine on original WorldEdit.

**How to replicate**:
Create a class that extends InputParser<Pattern>and register an instance of it with this method:
`WorldEdit.getInstance().getPatternFactory().register(parser);`

**Checklist**:

- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:16
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:16 UTC
