### ISSUE TITLE
SplitTask randomly crashes server due to wait in main thread

### ISSUE THREAD

**Issue by PinkLolicorn** [boy0001/FastAsyncWorldedit#1254] opened 2019-01-19 05:58 UTC
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**:
https://hastebin.com/agorecumoz

**Description of the problem:**
When using SplitTask server locks randomly and crashes. This rarely happens, occurred two times for several dozen runs. I have World#getBlockAt calls in my task. My task is similar to this from [example](https://github.com/boy0001/FastAsyncWorldedit/wiki/TaskBuilder#splittask-example). Is there a reason why this lock is placed in server's main thread?

Thread dump: https://pastebin.com/WALtam9e
Lock line: [here](https://github.com/boy0001/FastAsyncWorldedit/blob/dc2d2775171adfc4ea68d44059dcc63054f421c1/core/src/main/java/com/boydti/fawe/util/task/TaskBuilder.java#L530)

**How to replicate**:
Not figured it out.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [ ] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:13
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:13 UTC
