### ISSUE TITLE
Error loading schematic with NBT data

### ISSUE THREAD

**Issue by DaveDevil** [boy0001/FastAsyncWorldedit#1243] opened 2019-01-04 14:09 UTC
# Bug report

**Debug paste link**: https://hastebin.com/ferosezoqu.makefile

**Description of the problem:**

FastAsyncWorldEdit-bukkit-18.12.24-4198932-2085

Error if loading a schematic that contains item with NBT data. Here's the log of the error:

https://hastebin.com/esutuxipel.md

**How to replicate**:

Take a chest and a book&quill. Write something in the book, and put it in the chest. Select che chest and //copy. If you //paste, it works perfectly.

Now save a schematic with /schematic save test. None errors.

Load the schematic with /schematic load test, the error appear in the console, and the schematic isn't loaded.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:12
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:12 UTC
