### ISSUE TITLE
FAWE doesnt respect PlotSquared restriction

### ISSUE THREAD

**Issue by theJ3H** [boy0001/FastAsyncWorldedit#1314] opened 2019-06-19 17:54 UTC
PlotSquared allows a plot owner to add a player to the plot as a member or as a trusted player.

https://github.com/IntellectualSites/PlotSquared/wiki/Commands#add
https://github.com/IntellectualSites/PlotSquared/wiki/Commands#trust

If a player is only added as a member the player can only build on the plot while the owner is online. FAWE doesn't respect that restriction and a member can use worldedit on the plot even if the owner is online.

https://github.com/boy0001/FastAsyncWorldedit/blob/f71043bea6ee350d9ef3977f69450a50f41b22d9/core/src/main/java/com/boydti/fawe/regions/general/plot/PlotSquaredFeature.java#L97

This should be adjusted so that a player can only use fawe as a plot member if the owner is online.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:16
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:16 UTC
