### ISSUE TITLE
FAWE and aSkyblock not working :(

### ISSUE THREAD

**Issue by QueenAngus** [boy0001/FastAsyncWorldedit#1297] opened 2019-05-11 14:37 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:

**Description of the problem:**

**How to replicate**:

**Checklist**:

- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

Hi there.
I am on FAWE latest version and server version 1.12.2. I'm trying to use FastAsyncWorldEdit on the latest version, aSkyblock on the latest version and have region-restrictions set to true in my fast async config. Players cannot world edit in restricted regions so that's perfect, however it fails to do the check to allow them to worldedit on their own island. They have permission fawe.askyblock. I tried fawe.aksyblock.member also but that didn't make a difference. Any help would be appreciated!

Debugpaste: https://athion.net/ISPaster/paste/view/4999552d3b4e4d64984dc186fcfd73ed

Thanks,
Angus

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:15
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:15 UTC
Labels: [?] Testing Required
