### ISSUE TITLE
Error when using /set with a region that contains a chunk with a chest

### ISSUE THREAD

**Issue by ProSl3nderMan** [boy0001/FastAsyncWorldedit#1248] opened 2019-01-10 04:36 UTC
# Bug report
Debug paste link: https://hastebin.com/oraxageqer

**Description of the problem:**
When ever you select a region that contains a chest or any block that opens an inventory (hopper, dropper, etc), and you do //set <any block>, it will avoid the chunk that contains the chest and spit out a console error. Console error here: https://hastebin.com/ofewibilif.shell
"WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.asInt()I"
There is another ticket or "issue" that someone else made back in January, 2018, but he is using sponge while I am using spigot. His was #854 .

**How to replicate**:
Here's a short 18 second video on how to replicate: https://youtu.be/c8YXv_Noyqg

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:12
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:12 UTC
