### ISSUE TITLE
Rotating clipboard breaks downloading schematic.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#1195] opened 2018-11-09 16:09 UTC
FastAsyncWorldEdit dev 1230
Paper dev 1587 (Spigot 1.12.2)

* Make a selection.
* Copy it to your clipboard ``//copy``
* Rotate the clipboard ``//rotate 90``
* Download the clipboard as a schematic ``//download``
* Paste the downloaded schematic in-game via the ``//schematic load url`` command.
* The schematic is pasting only air!

Copying a selection, rotating, and pasting in-game works fine. Copying a selection, downloading it, and pasting the schematic works fine. Just copying a selection, rotating the clipboard, then downloading it, the schematic clipboard breaks. As if the rotated clipboard is different than the plain copied clipboard.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:10
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:10 UTC
Labels: [✖] Cannot Replicate
