### ISSUE TITLE
World Edit Logger Issues

### ISSUE THREAD

**Issue by Saalty** [boy0001/FastAsyncWorldedit#1350] opened 2020-01-11 11:22 UTC
I am on 1.8 on fawe and I dont know if it is still supported. I have coreprotect enabled on the server and with the worldedit enabled, it spams loads in the chat: https://i.imgur.com/WxopsTk.png. So I already have debug disabled so add this to the config:

extent:
    allowed-plugins:
    - CoreProtect
 I also tried disabling world edit logger in the core protect config and am on the latest 1.8 version and the chat spam still occurs. I also tried installing BlocksHub but it completly breaks worldedit: https://i.imgur.com/54sLYIQ.png. I am really stuck. I just want to use world edit without chatspam or preferably while logging the worledit using coreprotect/blockshub. 

https://athion.net/ISPaster/paste/view/dde5165adc474dea98f258c7f0aae7c6

Thanks

**Comment by austind9999** [comment] 2020-05-02 20:19
I am having the same issues as well. My integration via BlocksHub and CoreProtect will not function and //rollback does not work. 

https://i.imgur.com/6Y4TspX.png
https://athion.net/ISPaster/paste/view/9dc08d2c9514466a8f600dfefcd7c133

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:17
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:17 UTC
