### ISSUE TITLE
"> <" replace modifiers aren't working correctly

### ISSUE THREAD

**Issue by StealWonders** [boy0001/FastAsyncWorldedit#1215] opened 2018-12-09 12:31 UTC
# Bug report

**Debug paste link**:
https://hastebin.com/orinagopot

**Description of the problem:**
The " > < " modifiers aren't working correctly.

**How to replicate**:
`//replace >grass 20%31:1,10%fern,5%38,75%0`

Current situation:
![2018-12-09_13 29 23](https://user-images.githubusercontent.com/6114858/49697358-9c516600-fbb6-11e8-9eb9-aa063869f291.png)

How it should be / used to be:
![2018-12-09_13 29 29](https://user-images.githubusercontent.com/6114858/49697359-a07d8380-fbb6-11e8-92bd-346ffc3abb7a.png)

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:11
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:11 UTC
