### ISSUE TITLE
Schematic won't paste on plot or auto-paste on claim (with or without FastAsyncWorldEdit)

### ISSUE THREAD

**Issue by NadeSwiiv** [boy0001/FastAsyncWorldedit#1178] opened 2018-10-29 19:47 UTC
# Bug report

**Debug paste link** : https://hastebin.com/oxixoqumul (PLOT DEBUG)

https://hastebin.com/hudavodeto (FAWE DEBUG)
**Description of the problem:** When I try to paste a 24x24 schematic (on a claimed plot) called PlotSquaredHouse1 by using /plot schematic paste PlotSquaredHouse1 the shecmatic doesn't paste, when I redo the commend it says "Task is already running". I've followed the instructions on https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim how to make and paste this schematic and have done all that was asked 

**How to replicate**:

Same as above, happend 3 times already.
**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:09
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:09 UTC
