### ISSUE TITLE
hollow buggy

### ISSUE THREAD

**Issue by IdrisMC** [boy0001/FastAsyncWorldedit#1299] opened 2019-05-12 13:11 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**: https://athion.net/ISPaster/paste/view/258894c2cebf44caba16f907bf15b7b9

**Description of the problem:**

Hollow doesnt work sometimes, dont know how to explain it so just look:
https://gyazo.com/cfdee536fc32113826e18cf6d7b41b6f
https://gyazo.com/fcfb11e875bcb97a4c7a49205bd1d946
**How to replicate**:

Make a big grass block, hollow it.
**Checklist**:

- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by PixelNotFound** [comment] 2019-05-19 07:39
Got this issue on both 1.12.2 and 1.13.2

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:15
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:15 UTC
