### ISSUE TITLE
Problems/errors with provided FAWE worldguard plz update to latest BETA (not dev) builds of worldguard if possible since most plugins that require WG build against this version

### ISSUE THREAD

**Issue by axemwa** [boy0001/FastAsyncWorldedit#1283] opened 2019-04-02 02:45 UTC
I get this error when using the provided FAWE worldguard

Using latest builds of FAWE and WorldGuard to date (and time) from https://ci.athion.net

The error(s)
https://pastebin.com/ey9c8NHH

**Comment by boy0001** [comment] 2019-04-02 02:55
Try using the latest FAWE and PlotSquared-breaking + Normal WorldGuard (so remove the FAWE-WorldGuard)

**Comment by axemwa** [comment] 2019-04-02 03:00
but I need worldguard for my regions?

**Comment by axemwa** [comment] 2019-04-02 03:00
oh nvm

**Comment by boy0001** [comment] 2019-04-02 03:00
Like I said, use the normal worldguard

**Comment by axemwa** [comment] 2019-04-02 03:01
ill try that but doesn't worldguard rely on worldedit which u need to remove for FAWE?

**Comment by axemwa** [comment] 2019-04-02 03:11
yeah as I thought, using FAWE + Original worldguard + plotsquared causes dependancy issues becuase original worldedit is missing. I'm not sure what plotsquared does but I normally don't use it.
also tried using FAWE + Original WorldGuard + Original Worldedit but becuase original Worldedit is there it sees it as an ambiguous (copy) plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:14
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:14 UTC
