### ISSUE TITLE
one operation per EditSession? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [boy0001/FastAsyncWorldedit#1214] opened 2018-12-08 13:52 UTC
Hello, I have to apologize first because I didn't know whether I'm doing it right or not, but I've searched for it a lot and didn't find an answer. 

So I have this piece of code setting a ground and clear up the upper area to air: 
```java
                // grass
                {
                    Region region = new CuboidRegion(
                            new Vector(loc.getX() + (tileX << 3), 64, loc.getZ() + (tileZ << 3)),
                            new Vector(loc.getX() + (tileX << 3) + 7, 64, loc.getZ() + (tileZ << 3) + 7)
                    );
                    editSession.setBlocks(region, new BaseBlock(2));
                }
                // air
                {
                    Region region = new CuboidRegion(
                            new Vector(loc.getX() + (tileX << 3), 65, loc.getZ() + (tileZ << 3)),
                            new Vector(loc.getX() + (tileX << 3) + 7, 128, loc.getZ() + (tileZ << 3) + 7)
                    );
                    editSession.setBlocks(region, new BaseBlock(0));
                }
                editSession.flushQueue(); // managed by this function
            } catch (Exception e) {
                e.printStackTrace();
            }
```

I used this function to create EditSession instances: 
```java
public EditSession createEditSession() {
        return MineClashPlugin.getPlugin().getWorldEdit().getEditSessionFactory().getEditSession(new BukkitWorld(world), 256 << 6, (com.sk89q.worldedit.entity.Player) null);
    }
```

And it seems only the first part of the editing made changes instead of both, could you please help me a bit? thanks!

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:11
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:11 UTC
