### ISSUE TITLE
Problem With Auto-Complete

### ISSUE THREAD

**Issue by jadsspt** [boy0001/FastAsyncWorldedit#1307] opened 2019-05-25 18:51 UTC
**Debug paste link**: https://github.com/boy0001/FastAsyncWorldedit/issues/1307#issue-448492232 (Log: https://hasteb.in/soxumiqa.md)

**Description of the problem:**

using tab to auto-complete (like d + tab should be dirt) doesnt do exactly what it does it just writes "cFor parameter 'to': Invalid block 'f'. See: //patterns" when pressed tab
![image](https://user-images.githubusercontent.com/47069768/58373409-be049680-7f25-11e9-83b4-d123aa82da23.png)
I Maked Sure that no plugins was interrupting Fawe... tried vanilla minecraft with a server that only had FAWE..
No Errors In Console.

**How to replicate**:

- do a selection
- do //set d + tab
- it was supposed to write //set dirt. but it writes 
"//set cFor parameter 'to': Invalid block 'd'. See: //patterns"

**Checklist**:

- [x] I made sure that I'm using FAWE on 1.12.2 or lower
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)]
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by jadsspt** [comment] 2019-05-25 18:52
the debug paste link is from my skywars server but everything didn't work at all in my servers.
this happened from a flick of eyes

**Comment by jadsspt** [comment] 2019-05-25 20:01
Fawe Debug Paste.... : https://athion.net/ISPaster/paste/view/400158cbbcff4a6782c3b4763b52798d

**Comment by xTHEV0iDx** [comment] 2020-02-19 16:54
BUMP? This still is an ongoing issue. typing commands out is very time consuming. When will this be resolved?

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:15
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:15 UTC
