### ISSUE TITLE
Rotate and Flip error

### ISSUE THREAD

**Issue by zWyrn** [boy0001/FastAsyncWorldedit#1240] opened 2019-01-02 06:35 UTC
**Debug paste link**:
https://hastebin.com/vebumaduxe

**Description of the problem:**
Rotate und Flip don't works, datas are not saved and not change the facing location
http://prntscr.com/m22l3r
Left how it is, right how it should be

Tried with //rotate 90 and //paste
and tried with //flip w and //paste

Using newest Spigot (patched with Buildtools)
and newest dev versions of Fawe

**Checklist**:
- [x] I included a `/fawe debugpaste` link 
- [ ] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Draycia** [comment] 2019-01-02 06:44
See issues: 1079, 1104, 1203, 1235

**Comment by zWyrn** [comment] 2019-01-02 06:54
Yea, but there is not really a helpful answer.
"Fixed:

Fixing block rotations on copy/paste"
But its not fixed?
Or is anywhere a new version of fawe available?

Greets

**Comment by Draycia** [comment] 2019-01-02 06:59
It has not been fixed yet, it's still on the TODO list.

**Comment by zWyrn** [comment] 2019-01-02 07:01
Sure, but under fixed i understand that its fixed, lol.

**Comment by Cazitron** [comment] 2019-01-03 22:56
I'd love to know why fixing one of your most used functions in FAWE and is nearly one of the main reasons why people get world edit, is not a top priority. Surely it has to be up there with basic functionality...

**Comment by Draycia** [comment] 2019-01-03 23:01
Well there's around 4 people working on FAWE and all of them have lives. 
Lead dev has been MIA for the past 3 months. 
And they need to work on the WE7 update.

They don't have the resources to prioritize things the way you want.

**Comment by N0tMyFaultOG** [comment] 2019-01-09 19:59
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1104

**Closed by N0tMyFaultOG** 2019-01-09 19:59 UTC
