### ISSUE TITLE
NBT data is not copy/pasting correctly with FAWE 1.13.

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncWorldedit#1192] opened 2018-11-08 17:11 UTC
Paper dev 432
FAWE 1.13 dev 99

NBT data inside chests and in builds does not seem to be copying/pasting correctly with FAWE 1.13. Taking a 1.12 FAWE build/chest schematic and pasting it in a 1.13 environment with FAWE 1.13, all NBT data is stripped from items. NBT data such as player head skull data (skin), tool item flags (such as unbreakable), and more.

**Comment by Tsoccerguy3** [comment] 2019-05-15 16:53
Also related , Schematic made in 1.12.2 (maybe older versions ) , the block state of corner stairs is pasted incorrectly in 1.13.2 . The stair state for corners is not correct .

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:09
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:09 UTC
Labels: 1.13.X
