### ISSUE TITLE
Cannot send chat message

### ISSUE THREAD

**Issue by EazyFTW** [boy0001/FastAsyncWorldedit#1245] opened 2019-01-06 20:57 UTC
# Bug report

**Debug paste link**:

**Description of the problem:**
'Cannot send chat message' pops up after using commands too much.

**How to replicate**:
Unknown.

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by CaliDreams** [comment] 2019-01-09 19:30
This is also happening to me, and I haven't been able to replicate it on a consistent basis. It seems to occur most after too quick of an /undo following a paste.

**Comment by Draycia** [comment] 2019-01-09 19:35
@EazyFTW Please submit a debugpaste as the issue template asks you to do.

**Comment by CaliDreams** [comment] 2019-01-09 21:52
Here's my debugpaste:
https://hastebin.com/azifomahex

On a 1.13.2 Spigot server using FastAsyncWorldEdit-bukkit-1.13.132 
-Has happened over seemingly all versions I've had since starting first 1.13 Snapshot server (I check FAWE for updates weekly)
-In last two or so updates, seems to be happening to players now who don't have access to FAWE at all but it's giving exactly the same message word for word in salmon color and blocking use of chat/commands till they relog
Hope that helps!

**Comment by EazyFTW** [comment] 2019-01-09 22:37
I can confirm it happens after /undo sometimes. I'm not gonna submit a debug paste as Cali has and I know it has nothing to do with my plugins.

**Comment by prototype464** [comment] 2019-01-10 01:45
I can confirm this has happened to me as well and it does indeed happen more often when using //undo too quickly and often.

**Comment by navett52** [comment] 2019-01-15 06:39
It happens when you use certain commands and then undo them. Two commands I know that are affected are flip and stack.

Paste: https://hastebin.com/doxuwicate

How to replicate:
Use the stack or flip command, then undo your edit. You will then get "cannot send chat message" anytime you try to send one, command or no. It's unregistering you from the server, even though you're still online.

**Comment by Kirrasio** [comment] 2019-01-26 23:34
I am also confirming and it's been happening for a little under a month, I feel like this is happening more frequently than it was. Will there be a fix for this soon?

**Comment by N0tMyFaultOG** [comment] 2019-01-26 23:38
We are aware of the issue, join our [discord](https://discord.gg/ebreupz) to receive notifications about major updates, fixes and changes.

**Comment by CaliDreams** [comment] 2019-03-05 20:36
--Hoping to help with extra detail updates, not nagging--

Triggers:
//stack
//stack then /undo
//flip then /undo, sometimes //flip without undo
//paste then /undo

Facts: 
-Don't have to be in the chunk, specified region or worldedit selection, or even have the chunks loaded that you're changing for this to trigger
-Now happens to any players online at the time, inconsistently - usually effects 1/2 to 2/3rds of whoever is online, who don't have to have access to any worldedit permissions or be anywhere near effected area
-Requires relog to solve

Tested on:
-Spigot 1.13.2 3cb9dcb-1dbe87c "latest version" downloaded the day of this reply
-On server with NO plugins at all except for FastAsyncWorldEdit-bukkit-1.13.135 downloaded today directly from empcraft.com and the DummyFawe.jar it generates

-I'm aware you guys are busy and aware of this issue, and have been on your Discord for several months
I'm nudging on this issue again simply to deliver fact updates after testing again today, and because this is by far my server's most pressing issue, of all the bugs currently happening with FAWE.

Ty for all the hard work you guys are doing, hope this helps!

**Comment by TheCyberCode** [comment] 2019-04-02 17:40
I'm also having the same issue.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:12
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:12 UTC
Labels: 1.13.X
