### ISSUE TITLE
Lost more efficiency on 1.13.1 :/

### ISSUE THREAD

**Issue by xCraftRayX** [boy0001/FastAsyncWorldedit#1150] opened 2018-10-07 18:57 UTC
# Bug report

**Debug paste link**:
https://hastebin.com/xefixiwiqo

**Description of the problem:**
Hi, I'm using this plugin in my minigame, but from 1.13 I have some problem with efficiency :/
Chunks load late rather than at the same time like in 1.12 version of Spigot.
I don't know maybe problem is with code, because I rewriting my plugin for 1.13 and I left support for MaterialData, because currently we can use material for example: BLUE_WOOL
My part of code: https://hastebin.com/moxogecewi.cs
My previous code: https://hastebin.com/ihovigilaz.cs

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:08
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:08 UTC
Labels: 1.13.X
