### ISSUE TITLE
Askyblock Fawe

### ISSUE THREAD

**Issue by justinbea** [boy0001/FastAsyncWorldedit#1252] opened 2019-01-14 20:19 UTC
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**:
https://hastebin.com/lasixuvize (region-restrictions: true changed later but didnt helped whas for testing)

**Description of the problem:**
https://gyazo.com/111af232dcb08c2ded9b3a2584dc9cec
https://gyazo.com/6b06d3747681d8b319dd412e511f8374

**How to replicate**:
select region
//set 1

i want worldedit support on my skyblock server ive game them the permissions to worldedit and the askyblock and askyblock.member permission listed in the permissions node but still the player gets an error message that he is not allowed becouse of the region even if he is an island owner or member

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:12
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:12 UTC
