### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by arturek1666** [boy0001/FastAsyncWorldedit#1230] opened 2018-12-19 12:33 UTC
# Bug report

**Debug paste link**:

Somehow it doesn't work :( 
https://hastebin.com/qozanimazu
**Description of the problem:**

Every time a player join a server gives a big spam of error:
https://pastebin.com/TsFzDx72
I use paperspigot 1.13.2#486
**How to replicate**:
Not sure how to replicate it just happens when a player join the server.

**Comment by MrAmos123** [comment] 2018-12-19 13:38
Same issue.

https://github.com/PaperMC/Paper/issues/1741

According to a dev of Paper, the issue seems to be related to FAWE.

**Comment by N0tMyFaultOG** [comment] 2018-12-19 16:15
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Closed by N0tMyFaultOG** 2018-12-19 16:15 UTC
