### ISSUE TITLE
Pasting operation happens though parts are invisible

### ISSUE THREAD

**Issue by q220** [boy0001/FastAsyncWorldedit#1170] opened 2018-10-23 15:19 UTC
# Bug report
Some of our users report issues when doing operations such as pasting. FAWE reports that the operation is queued, with the amount of blocks in parentheses. Then some parts of paste are viewable by the client and the rest is not. However when the client flies/runs into the area where the paste was expected to have pasted something, the client gets rubberbanded/blocked from entering. This seems to mean that for the server there is supposed to be blocks there.

When the client forces the reloading of chunks with F3+A the pasted content does not reappear.
**Debug paste link**:
https://hastebin.com/ecajopuvef

**Description of the problem:**
No errors are shown.

**How to replicate**:
Currently still trying to find out how it can be replicated. But right now the issue only seems to happen when the server has been running for a while. The problem does not happen right after a server restart.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:09
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:09 UTC
