### ISSUE TITLE
Please, fix region restrictions

### ISSUE THREAD

**Issue by Sitmobedaf** [boy0001/FastAsyncWorldedit#1233] opened 2018-12-20 00:43 UTC
Currently, the region restrictor does not work with the latest version of the plugin.

**Comment by Blitheness** [comment] 2018-12-29 04:21
On my server, I get the errors seen here
https://github.com/boy0001/FastAsyncWorldedit/issues/1232

When a player that should have worldguard region restrictions tries to use FAWE.

Are you getting exceptions like this?

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:12
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:12 UTC
