### ISSUE TITLE
FAWE - Very Buggy

### ISSUE THREAD

**Issue by AccioAce** [boy0001/FastAsyncWorldedit#1224] opened 2018-12-16 03:34 UTC
FAWE is very buggy. //copy, //set air, etc it gives us a error and also it spams console with errors. There are quite some major error which i hope you can get it fix asap. 

- Thanks :)

**Comment by lolita-is-godddd** [comment] 2018-12-16 09:03
plz show log, and it will start from there.

**Comment by N0tMyFaultOG** [comment] 2018-12-18 18:00
https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Comment by N0tMyFaultOG** [comment] 2018-12-18 18:01
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Closed by N0tMyFaultOG** 2018-12-18 18:00 UTC
