### ISSUE TITLE
Bug with lighting & shadow calculation for leaf blocks

### ISSUE THREAD

**Issue by bkane2** [boy0001/FastAsyncWorldedit#1375] opened 2020-05-08 01:54 UTC
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:
The '/fawe debugpaste' command fails with a 503 status code.

Our FAWE version is 'FAWE 18.7.21-a00345f-1159 by Empire92'.

**Description of the problem:**
Hi, I'm a builder from the [WesterosCraft](https://westeroscraft.com) team.

Leaf blocks which are generated using WE do not appear to calculate lighting and shadows correctly, at least as of the version of FAWE we use for minecraft 1.11.2.

If I set a large cube of some solid block (e.g. wool), it correctly calculates shadows underneath. If I press F3 and look at the value for "light", this value decreases as I walk underneath the wool blocks.

However, if I set a large cube of leaf blocks, the shadow calculation breaks. If I press F3 and look at the value for "light" underneath them, the value is always 15 (max lighting) even though it's not exposed to full sunlight. If I place the leaf blocks by hand (or edit them in using Voxel brushes), it calculates the shadows correctly.

Using the //fixlighting commands also causes lighting underneath leaf blocks to break, changing all the light values to 15. It would be great if this command especially were fixed, since a large part of our forests have already been WE'd in and hence do not have realistic lighting currently.

**How to replicate**:
Just set a large cube of some solid block (e.g. wool), and press F3 while standing underneath it to check light values. Then set a large cube of leaf blocks and check light values underneath it. If needed, place a large cube of leaf blocks by hand and stand underneath it to compare.

Note that we're using FAWE (version above) for Minecraft 1.11.2. I'm not sure if this issue has been fixed since then, or if it would be possible to fix this issue for the version we're using. But it would make a big difference for our project. Thanks!

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:19
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:19 UTC
