### ISSUE TITLE
InventoryMode 1

### ISSUE THREAD

**Issue by Trenly** [boy0001/FastAsyncWorldedit#1199] opened 2018-11-12 21:39 UTC
# Bug report

**Description of the problem:**

In inventory-mode 1, it is possible to place blocks you do not have

**How to replicate**:

Using the version for 1.7-1.12
Set inventory mode to 1 in the config
In game- remove all bypass permissions so it will use blocks from your inventory
Part 1:
   Put 1 stone (1:0) in your inventory
   Select a 1 block region and do //set 1:5  
   Andesite will be placed instead of the stone

Part 2:
   Clear your inventory
   Select a region
   Do //set 117
   Do //set {any block id}
   Any block can be //set without having it in your inventory

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:10
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:10 UTC
