### ISSUE TITLE
Error on //paste in lastest version

### ISSUE THREAD

**Issue by zeronerve** [boy0001/FastAsyncWorldedit#1341] opened 2019-12-19 20:20 UTC
Hi, I'm using that latest FAWE build on Paper1.14.4 (also latest build). I'm
receiving this error after //copy //flip //paste...

`[13:28:09 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.extent.transform.BlockTransformExtent.cache(BlockTransformExtent.java:385) ~[?:?]
        at com.sk89q.worldedit.extent.transform.BlockTransformExtent.<init>(BlockTransformExtent.java:103) ~[?:?]
        at com.sk89q.worldedit.session.PasteBuilder.build(PasteBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:463) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:354) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$17(PlatformCommandManager.java:673) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:689) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:675) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$15(PlatformCommandManager.java:645) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
`

**Comment by zeronerve** [comment] 2019-12-19 20:23
# Server Information
server.platform: bukkit
server.version: git-Paper-237 (MC: 1.14.4)
Plugins: 
 - CleanroomGenerator: 1.1.0
 - WorldEdit: 1.15-6;e12b26c
 - FastAsyncWorldEdit: 1.14
 - Essentials: 2.17.1.0
 - VoxelSniper: 1.0.2
 - EssentialsChat: 2.17.1.0
 - PermissionsEx: 1.23.4
 - Modifyworld: 1.19.7
 - PerWorldInventory: 2.3.1
 - PlotSquared: 4.400
 - Votifier: 3.0.0-SNAPSHOT
 - ProtocolSupport: 4.29-dev
 - BanManager: 6.0.2
 - BungeeTabListPlus: 2.8.11
 - Multiverse-Core: 4.0.0-b766
 - ProtocolLib: 4.5.0-SNAPSHOT
 - ArmorStandTools: 3.4.0
 - ChatControl: 8.4.13
 - HolographicDisplays: 2.4.0
 - Multiverse-Portals: 4.0.0-b799
 - TouchscreenHolograms: 1.4.1



# YAY! Now, let's see what we can find in your JVM
memory.free: 1160446648
memory.max: 3279945728
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_201'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '5.1.2-x86_64-linode124'

**Comment by zeronerve** [comment] 2019-12-21 19:29
This happens in both Paper and Spigot 1.14.4, with no other plugins loaded. It only happens when the clipboard is manipulated with //flip or //rotate

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:17
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:17 UTC
