### ISSUE TITLE
[Error] After changed the "Held item slot"

### ISSUE THREAD

**Issue by momoservertw** [boy0001/FastAsyncWorldedit#1228] opened 2018-12-19 07:35 UTC
# Bug report
[15:23:54 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTBase.b_()Ljava/lang/String;
[15:23:54 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:437)
[15:23:54 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410)
[15:23:54 WARN]:        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:66)
[15:23:54 WARN]:        at com.boydti.fawe.bukkit.v0.BukkitQueue_0.toNative(BukkitQueue_0.java:179)
[15:23:54 WARN]:        at com.boydti.fawe.bukkit.util.ItemUtil.getNBT(ItemUtil.java:71)
[15:23:54 WARN]:        at com.sk89q.worldedit.bukkit.BukkitItemStack.getNbtData(BukkitItemStack.java:63)
[15:23:54 WARN]:        at com.boydti.fawe.util.BrushCache.getTool(BrushCache.java:41)
[15:23:54 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:961)
[15:23:54 WARN]:        at com.sk89q.worldedit.LocalSession.getTool(LocalSession.java:956)
[15:23:54 WARN]:        at com.boydti.fawe.bukkit.listener.BrushListener.onPlayerItemHoldEvent(BrushListener.java:38)
[15:23:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:23:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:23:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:23:54 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:23:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[15:23:54 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:23:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:23:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1408)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInHeldItemSlot.a(SourceFile:30)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInHeldItemSlot.a(SourceFile:8)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[15:23:54 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:23:54 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[15:23:54 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[15:23:54 WARN]:        at java.lang.Thread.run(Unknown Source).

**Debug paste link**:
https://hastebin.com/odizuxaqag

**Description of the problem:**
After you changed the "Held item slot" to another one, the console will get this error sometimes.

**Comment by N0tMyFaultOG** [comment] 2018-12-19 08:55
Duplicate of #1213

**Closed by N0tMyFaultOG** 2018-12-19 08:55 UTC
