### ISSUE TITLE
//up teleportation doesn't cancelled without permission

### ISSUE THREAD

**Issue by Aurelien30000** [boy0001/FastAsyncWorldedit#1272] opened 2019-02-19 14:42 UTC
# Bug report for FastAsyncWorldEdit <1.12.2

**Debug paste link**:

Here -> https://hastebin.com/dofejuyexo

**Description of the problem:**

When i give this permission to a player (fawe.permpack.basic), it shouldn't be able to use the //up command in non-authorized regions.
But, even if the command is correctly cancelled (the glass block is not placed and an error message is sent : no permission), the teleportation is not cancelled and it's a bit problematic.

**How to replicate**:

- _I think WorldGuard is necessary_
- Give this permission to a non-op player -> fawe.permpack.basic
- Set "region-restrictions" to true in the config
- Type //up in your world and see the result

**Checklist**:

- [V] I included a `/fawe debugpaste` link
- [V] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [V] I made sure I am using an up-to-date version of [FAWE <1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [V] I made sure the bug/error is not caused by any other plugin

I hope that I provided you all the information that you need. Don't hesitate to ask me if necessary.
Thank you :)

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:13
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:13 UTC
