### ISSUE TITLE
Error on copy

### ISSUE THREAD

**Issue by F1b3rDEV** [boy0001/FastAsyncWorldedit#1222] opened 2018-12-15 16:57 UTC
[17:54:31 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.NBTTagInt.e()I
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:422) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.toNative(Spigot_v1_13_R2.java:410) ~[?:?]
        at com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2.getEntity(Spigot_v1_13_R2.java:317) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitEntity.getState(BukkitEntity.java:83) ~[?:?]
        at com.sk89q.worldedit.function.entity.ExtentEntityCopy.apply(ExtentEntityCopy.java:97) ~[?:?]
        at com.sk89q.worldedit.function.visitor.EntityVisitor.resume(EntityVisitor.java:70) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[?:?]
        at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:359) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:68) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.lambda$copy$0(ClipboardCommands.java:180) ~[?:?]
        at com.boydti.fawe.object.FawePlayer.checkConfirmationRegion(FawePlayer.java:237) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:162) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:265) ~[?:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:133) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$2.get(CommandManager.java:414) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:437) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:418) ~[?:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:536) ~[?:?]
        at com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:328) ~[?:?]
        at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-480]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-480]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-480]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by N0tMyFaultOG** [comment] 2018-12-18 18:00
https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Comment by N0tMyFaultOG** [comment] 2018-12-18 18:00
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Closed by N0tMyFaultOG** 2018-12-18 18:00 UTC
