### ISSUE TITLE
Rotate/Paste + Stairs and Fences

### ISSUE THREAD

**Issue by Vanillezucker** [boy0001/FastAsyncWorldedit#1203] opened 2018-11-22 19:00 UTC
# Bug report
**Description of the problem:**

When rotating and/or pasting, stairs and fences are placed wrongly.
(Paper 1.13.2)

**Comment by N0tMyFaultOG** [comment] 2018-11-22 19:02
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1104

**Closed by N0tMyFaultOG** 2018-11-22 19:02 UTC
