### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mrfloris** [boy0001/FastAsyncWorldedit#1200] opened 2018-11-14 17:04 UTC
Welp, I would love to be compliant with the template reporting this, but I can't run the required commands, I get errors.

```>fawe debugpaste
[18:00:45 INFO]: (FAWE) There was an error handling a FAWE command: [See console]
[18:00:45 INFO]: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[18:00:45 ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
javax.net.ssl.SSLException: Received fatal alert: record_overflow```

Here's my reported issue:

```[17:43:35 INFO]: Set PluginClassLoader as parallel capable
>WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sk89q.worldedit.bukkit.WorldEditPlugin (file:/dev/MinecraftServer/mc-1.13.2-test-upgrade/plugins/FastAsyncWorldEdit-bukkit-18.11.14-ec22c4f-2071.jar) to field java.util.logging.Logger.name
WARNING: Please consider reporting this to the maintainers of com.sk89q.worldedit.bukkit.WorldEditPlugin```

And i would love to report it to worldedit, but the FAWE download page tells me to not install it, and use FAWE, so .. I feel like I have to come here. 

```>about FastAsyncWorldEdit
[18:03:36 INFO]: FastAsyncWorldEdit version 1.0
>about
[18:03:38 INFO]: This server is running CraftBukkit version git-Spigot-5696c83-c2035aa (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:03:38 INFO]: Checking version, please wait...
[18:03:38 INFO]: You are running the latest version
>```

Doing `pl` it seems FAWE has loaded, other console log entries indicate this as well. I thought I'd at least report back. I hope this helps development, and my apologies for being unstable this time to comply to the desired template.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:10
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:10 UTC
Labels: 1.13.X
