### ISSUE TITLE
Cannot transfer an armor-stand from Minecraft 1.12 to Minecraft 1.13

### ISSUE THREAD

**Issue by Mario359** [boy0001/FastAsyncWorldedit#1084] opened 2018-08-21 10:35 UTC
# Bug report

**Debug paste link**: https://hastebin.com/epogejikuj

**Description of the problem:** 

Schematics from Minecraft 1.12 (in .schematic not .nbt format) with a modified armor-stand can be loaded (//schem load armorstand) but not pasted (//paste) on Minecraft 1.13
I get this error:
```
[12:21:03 WARN]: net.minecraft.server.v1_13_R1.ReportedException: Loading entity NBT
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.Entity.f(Entity.java:1758)
[12:21:03 WARN]:        at com.boydti.fawe.bukkit.adapter.Spigot_v1_13_R1.readTagIntoEntity(Spigot_v1_13_R1.java:184)
[12:21:03 WARN]:        at com.boydti.fawe.bukkit.adapter.Spigot_v1_13_R1.createEntity(Spigot_v1_13_R1.java:305)
[12:21:03 WARN]:        at com.boydti.fawe.bukkit.v0.BukkitChunk_All.call(BukkitChunk_All.java:147)
[12:21:03 WARN]:        at com.boydti.fawe.example.DefaultFaweQueueMap.next(DefaultFaweQueueMap.java:138)
[12:21:03 WARN]:        at com.boydti.fawe.example.MappedFaweQueue.next(MappedFaweQueue.java:213)
[12:21:03 WARN]:        at com.boydti.fawe.util.SetQueue$1.run(SetQueue.java:165)
[12:21:03 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:21:03 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[12:21:03 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:21:03 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
[12:21:03 WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:60)
[12:21:03 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:493)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:518)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:286)
[12:21:03 WARN]:        at net.minecraft.server.v1_13_R1.Entity.f(Entity.java:1678)
[12:21:03 WARN]:        ... 13 more
[12:21:03 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
[12:21:03 WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[12:21:03 WARN]:        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
[12:21:03 WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
[12:21:03 WARN]:        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
[12:21:03 WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:46)
[12:21:03 WARN]:        ... 18 more
```

**How to replicate**:

Create a schematic from Minecraft 1.12 with a special armor-stand or download this: http://www.mediafire.com/file/0z0hq8yc4h72t9x/armorstand.schematic/file
Load and paste the schematic to Minecraft 1.13 (//schem load <name/armorstand> //paste)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:06
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:06 UTC
Labels: 1.13.X, [‼] high priority
