### ISSUE TITLE
Region Restriction broken?

### ISSUE THREAD

**Issue by Lateralus46n2** [boy0001/FastAsyncWorldedit#1345] opened 2019-12-24 19:15 UTC
[REQUIRED] FastAsyncWorldEdit Configuration Files:
https://athion.net/ISPaster/paste/view/1877d49c30dd4c94b84a0293daeeb7f3

[REQUIRED] FastAsyncWorldEdit Version Number:
Latest, from the download link under FAWE Forge 1.12

[REQUIRED] Spigot/Paper Version Number:
Forge 1.12.2 v838 (last three #'s in version)

[REQUIRED] Description of the problem:
I dont know if this is a bug or not so im just going to say all that happened. I have FAWE (latest version) for 1.12.2 forge (version 838). The main problem is that i have region restrictions off and i still get region restricted, with /wea on and me as an op. Secondly // commands are being queued and then never happen.

How to replicate:
I dont know if it can be reproduced, but all i did was put FAWE fresh download into the server. Then disable region restrictions and still be region restricted.

Plugins being used on the server:
Cubic Chunks
Cubic WG
ForgeEssentials
CC World Edit
Inv Tweaks
Js

**Checklist**:

- [x] I made sure that I'm using FAWE on 1.12.2 or lower
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:17
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:17 UTC
