### ISSUE TITLE
VS: /b over problems

### ISSUE THREAD

**Issue by dordsor21** [boy0001/FastAsyncWorldedit#128] opened 2016-05-28 19:32 UTC
/b over in VS has been reported to occasionally occur on other plots (like other VS usages)

It also doesn't replace blocks properly. Using the following set of commands created the following pattern:

/b over d1      /vr 4      /v 5

![image](https://cloud.githubusercontent.com/assets/10080017/15629540/240302b6-2513-11e6-83fa-4eaaabda90d3.png)

**Comment by boy0001** [comment] 2017-03-06 15:58
Duplicate of #126

**Closed by boy0001** 2017-03-06 15:58 UTC
Labels: [!] Bug
