### ISSUE TITLE
Feature Request - FAWE active toggle?

### ISSUE THREAD

**Issue by CleanerOrc** [boy0001/FastAsyncWorldedit#114] opened 2016-05-16 01:46 UTC
Any way to add a toggle command to enable/disable FAWE for a user?  ie, when disabled, FAWE doesn't manage block placement?

I'm coming from a standpoint of not being able to upgrade to MC 1.9 because too many plugins will break that aren't being updated to 1.9.x    So gonna stay at 1.8.8 for a while till can figure out alternatives.

Occasionally we find an edit that doesn't work.  It would be nice this being beta release, to have a way to fallback to plain WorldEdit for those situations we find a particular FAWE (known) bug, without having to remove plugin and reboot to go back to WorldEdit temporarily.

- co

**Comment by RoboMWM** [comment] 2016-05-16 03:30
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/50

**Closed** 2016-05-18 05:09 UTC
