### ISSUE TITLE
Region-restrictions not working with Spigot 1.13.1 and Towny

### ISSUE THREAD

**Issue by ipozow** [boy0001/FastAsyncWorldedit#1136] opened 2018-09-19 00:09 UTC
# Bug report

**Debug paste link**:

Not working… 

**Description of the problem:**

This only happens with Spigot 1.13.1, since I tried the same config with Spigot 1.12.2 and works fine. 
The problem is that if region-restrictions is “true” in the config, and the player has the fawe.towny permission or fawe.towny.\*, the player can't use any WorldEdit command in the town nor the wild. 
In the 1.12.2 server with fawe.towny.\* I was able to modify anywhere in the town, but in the 1.13.1 one not. 
Also there is a difference when trying to modify a region outside the allowed: 
Outside the allowed region: “Your WorldEdit action was cancelled: No allowed region”
But inside the allowed region: “Outside allowed region”
![2018-09-18_20 46 13](https://user-images.githubusercontent.com/10505413/45722984-7010e500-bb85-11e8-883a-909a7c8f693c.png)

Also I have tried using MySQL database for Towny and flatfile, an older version and a newer one and is the same for 1.13.1.

**How to replicate**:

1. Download the latest version of Spigot
2. Install the latest version of FAWE
3. Install Towny http://towny.palmergames.com/release-version-towny-advanced-0-93-0-0-1-11-1-13/
4. Install a permissions plugin like PermissionsEx
5. Add the fawe.towny.* permission to the player + the basic permissions for editing fawe.permpack.basic 
6. Disable using_economy in Towny config 
7. Create a town /t new town
8. Make a edition with WorldEdit inside the town

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:08
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:08 UTC
Labels: 1.13.X
