### ISSUE TITLE
Invalid key translated no permission message

### ISSUE THREAD

**Issue by ForceUpdate1** [boy0001/FastAsyncWorldedit#1361] opened 2020-03-23 14:14 UTC
FAWE 1.15 Build 139

Key: fawe.error.no.perm
Config-Key: error.no_perm

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/5feac07bf038243bc5f2c0e5037455f8374a1e68/worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java#L714

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/8aaed49fa6d5a7a204c3d238c60fa5a150338263/worldedit-core/src/main/resources/de/message.yml#L43

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:18
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:18 UTC
