### ISSUE TITLE
Fawe API making server crash

### ISSUE THREAD

**Issue by wiljafor1** [boy0001/FastAsyncWorldedit#1210] opened 2018-12-06 00:17 UTC
# Bug report
**Debug paste link**: https://hastebin.com/nomuxegoqi
**Code Plugin**
`private void executarDrill(Player p, Block b, Material material, byte data) {
		p.playSound(p.getLocation(), Sound.FIRE_IGNITE, 1.0f, 1.0f);
		Location l1 = b.getRelative(-1, 0, -1).getLocation();
		Location l2 = b.getRelative(1, -3, 1).getLocation();
		EnchantBlockEvent event = new EnchantBlockEvent(p, data, b, material, 8);
		Bukkit.getPluginManager().callEvent(event);
		EditSession session = BuildAPI.getEditSession(b.getLocation());
		Region region = new CuboidRegion(new Vector(l1.getBlockX(), l1.getBlockY(), l1.getBlockZ()),
				new Vector(l2.getBlockX(), l2.getBlockY(), l2.getBlockZ()));
		for (Vector pt : new FastIterator(region, session)) {
			Location loc = new Location(l1.getWorld(), pt.getX(), pt.getY(), pt.getZ());
			if (loc.getBlock().getType() != Material.AIR && m.getManager().getLib().getWorldUtils().isBreak(loc)) {
				try {
					session.setBlock(pt, new BaseBlock(0));
				} catch (MaxChangedBlocksException e) {
					e.printStackTrace();
				}
			}
		}
		session.flushQueue();
	}`
**Console**
`[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: ------------------------------
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: Current Thread: Craft Scheduler Thread - 35245
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 	PID: 1121782 | Suspended: false | Native: false | State: BLOCKED
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 	Stack:
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		com.boydti.fawe.example.NMSRelighter.fixSkyLighting(NMSRelighter.java:343)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		com.boydti.fawe.example.NMSRelighter.fixLightingSafe(NMSRelighter.java:284)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		com.boydti.fawe.example.NMSMappedFaweQueue$1.run(NMSMappedFaweQueue.java:47)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:48:44] [PaperSpigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)`

**Description of the problem:**
Crash server

**How to replicate**:
using the fawe edit session for a while it crashes the server

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:11
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:11 UTC
