### ISSUE TITLE
Player in modified chunks is killed

### ISSUE THREAD

**Issue by Artuto** [boy0001/FastAsyncWorldedit#1262] opened 2019-01-30 13:52 UTC
Bug report for FastAsyncWorldEdit 1.13.2

Debug paste link: https://hastebin.com/izodesajur

Description of the problem: When editing a chunk, if the player is inside the selection and then you cut, delete or set to air the player is killed but the client does not know about it.

For example:

![Bug](https://cdn.discordapp.com/attachments/486634680570085376/540164117843935273/unknown.png)

This happened, now you have to relogin so you can chat and send commands again.

How to replicate: 1- Set a selection
2- Make sure you're inside it.
3- Copy it and paste it somewhere.
4- Undo it
5- Check console.

Checklist:

[x] I included a /fawe debugpaste link

[x] I made sure there aren't duplicates of this report (Use Search)

[x] I made sure I am using an up-to-date version of FAWE 1.13.2

[x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2019-01-30 13:55
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1245

**Closed by N0tMyFaultOG** 2019-01-30 13:55 UTC
