### ISSUE TITLE
Entity dupe bug

### ISSUE THREAD

**Issue by Kixot14** [boy0001/FastAsyncWorldedit#410] opened 2017-02-02 04:10 UTC
Don't know how to explain this...
Just watch this wideo https://www.youtube.com/watch?v=9l_-ukldRq4

P.S. I not sure, maybe this bug on the WorldEdit side. Without FAWE it's still actual, but a little different...
(Created ticket on WE site http://dev.enginehub.org/youtrack/issue/WORLDEDIT-3542)

Can FAWE fix this bug ??

**Comment by boy0001** [comment] 2017-03-06 17:26
Duplicate of #210

**Closed by boy0001** 2017-03-06 17:26 UTC
