### ISSUE TITLE
//regen undo creates void

### ISSUE THREAD

**Issue by EvilOlaf** [boy0001/FastAsyncWorldedit#33] opened 2016-04-14 15:36 UTC
![2016-04-14_17 34 50](https://cloud.githubusercontent.com/assets/3305006/14533904/4ebd9904-0267-11e6-8477-1ad113de00b3.jpg)

Related to https://github.com/boy0001/FastAsyncWorldedit/issues/32

Tried `//undo` on the `//regen` show in the issue above completely replaced the area with void.

FAWE 3.3.10
WE 6.1.1 b3463

**Comment by boy0001** [comment] 2016-04-14 16:16
Duplicate of #32

**Closed by boy0001** 2016-04-14 16:16 UTC
