### ISSUE TITLE
//hcyl %1515

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#594] opened 2017-06-18 16:03 UTC
```
[17:59:56] [Server thread/INFO]: Player issued server command: //hcyl %1515
[17:59:56] [Craft Scheduler Thread - 3100/ERROR]: [WorldEdit] An unexpected error occurred while handling a FAWE command
com.sk89q.minecraft.util.commands.WrappedCommandException: java.lang.reflect.InvocationTargetException
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:264) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:380) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2$1.run(CommandManager.java:449) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer$1.run(FawePlayer.java:140) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:168) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:215) [FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$2.run(CommandManager.java:446) [FastAsyncWorldEdit-bukkit18.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor562.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:221) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	... 12 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_121]
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_121]
	at com.sk89q.worldedit.internal.expression.parser.Parser.peek(Parser.java:385) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.internal.expression.parser.Parser.parseStatements(Parser.java:302) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.internal.expression.parser.Parser.parse(Parser.java:83) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.internal.expression.parser.Parser.parse(Parser.java:79) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.internal.expression.Expression.<init>(Expression.java:110) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.internal.expression.Expression.<init>(Expression.java:89) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.internal.expression.Expression.compile(Expression.java:85) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.factory.HashTagPatternParser.parseFromInput(HashTagPatternParser.java:89) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.extension.factory.HashTagPatternParser.parseFromInput(HashTagPatternParser.java:27) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:57) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.internal.command.WorldEditBinding.getPattern(WorldEditBinding.java:213) ~[WorldEdit.jar:?]
	at sun.reflect.GeneratedMethodAccessor562.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.sk89q.worldedit.util.command.parametric.BindingHelper.bind(BindingHelper.java:167) ~[WorldEdit.jar:?]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:221) ~[FastAsyncWorldEdit-bukkit18.jar:?]
	... 12 more
```

```
[18:02:35 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
```

```
>fawe version
[18:02:59 INFO]:  » FAWE: FAWE 17.6.17-b2261bb-720 by Empire92
[18:02:59 INFO]: ------------------------------------
[18:02:59 INFO]:  - DATE: 17-Jun-2017 00:00:00
[18:02:59 INFO]:  - COMMIT: b2261bb
[18:02:59 INFO]:  - BUILD: #720
[18:02:59 INFO]:  - PLATFORM: bukkit
[18:02:59 INFO]:  - UPDATES: DISABLED
[18:02:59 INFO]: ------------------------------------
[18:02:59 INFO]:  » FAWE: WorldEdit (unknown) by sk89q
[18:02:59 INFO]: ------------------------------------
[18:02:59 INFO]: Platforms:
[18:02:59 INFO]:  - Bukkit-Official (6.1.8-SNAPSHOT;3689-b557b2b)
[18:02:59 INFO]: Capabilities:
[18:02:59 INFO]:  - GAME_HOOKS: Bukkit-Official
[18:02:59 INFO]:  - CONFIGURATION: Bukkit-Official
[18:02:59 INFO]:  - USER_COMMANDS: Bukkit-Official
[18:02:59 INFO]:  - PERMISSIONS: Bukkit-Official
[18:02:59 INFO]:  - WORLDEDIT_CUI: Bukkit-Official
[18:02:59 INFO]:  - WORLD_EDITING: Bukkit-Official
[18:02:59 INFO]: ------------------------------------
[18:02:59 INFO]: Wiki: https://github.com/boy0001/FastA
```

**Comment by dordsor21** [comment] 2017-06-18 16:05
well it's not a valid command, also effective duplicate of #558 and #559

**Closed by dordsor21** 2017-06-18 16:05 UTC
