### ISSUE TITLE
Fawe places dirt (wrong block)

### ISSUE THREAD

**Issue by Fliens** [boy0001/FastAsyncWorldedit#1368] opened 2020-04-14 01:53 UTC
Hi I‘m running a 1.15.2 paperMC Server with Fawe and plotsquared. When using set or replace command, the new set block gets replaced with dirt(even though I‘ve placed something different). It seems like the new placed block gets replaced with dirt when it gets updated(block placed next to it) or when the block is surrounded by blocks on all faces(Sometimes does not need any of these conditions).
When starting the server fawe creates dummy Worldedit

**Comment by Govindass** [comment] 2020-04-16 12:41
paper didn't exist in 1.5.2

**Comment by Fliens** [comment] 2020-04-16 13:03
> paper didn't exist in 1.5.2, spigot had only started gaining popularity

Oh i meant 1.15.2 im sorry

**Comment by Raphy123** [comment] 2020-04-22 11:00
Same bug ! Thank you

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:19
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:19 UTC
