### ISSUE TITLE
Change the language to report an error

### ISSUE THREAD

**Issue by mcfenmap** [boy0001/FastAsyncWorldedit#1360] opened 2020-03-21 20:03 UTC
language: "cn"

`[03:58:19 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@5010cc1b to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:246) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.access$200(WorldEditPlugin.java:104) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:640) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:453) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[Paper-1.15.2-b143.jar:git-Paper-142]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 13 more
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putAll(Unknown Source) ~[?:1.8.0_202]
        at com.sk89q.worldedit.util.translation.TranslationManager.tryLoadTranslations(TranslationManager.java:127) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.getTranslationMap(TranslationManager.java:150) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.lambda$new$0(TranslationManager.java:68) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer$1.translation(FriendlyComponentRenderer.java:51) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.render(FriendlyComponentRenderer.java:100) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.render(FriendlyComponentRenderer.java:59) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.lambda$deepRender$0(FriendlyComponentRenderer.java:83) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_202]
        at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_202]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.deepRender(FriendlyComponentRenderer.java:83) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.render(FriendlyComponentRenderer.java:62) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.lambda$deepRender$0(FriendlyComponentRenderer.java:83) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_202]
        at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_202]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.deepRender(FriendlyComponentRenderer.java:83) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.FriendlyComponentRenderer.render(FriendlyComponentRenderer.java:62) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:162) ~[?:?]
        at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:55) ~[?:?]
        at com.sk89q.worldedit.util.formatting.WorldEditText.reduceToText(WorldEditText.java:96) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.lambda$registerCommands$4(BukkitServerInterface.java:178) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_202]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_202]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_202]
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.registerCommands(BukkitServerInterface.java:181) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.registerCommandsWith(PlatformCommandManager.java:586) ~[?:?]
        at com.sk89q.worldedit.extension.platform.Capability$2.initialize(Capability.java:58) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:192) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformReady(PlatformManager.java:308) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 13 more`

**Comment by mcfenmap** [comment] 2020-03-21 20:05
The plug-in does not work properly after an error occurs

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:18
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:18 UTC
