### ISSUE TITLE
fawe.permpack.basic no longer functioning

### ISSUE THREAD

**Issue by MCAlagaesia** [boy0001/FastAsyncWorldedit#1221] opened 2018-12-15 14:54 UTC
# Bug report

**Debug paste link**: There is no output for the command "/fawe debugpaste" in either the console or in-game.

**Description of the problem:**
Users who were able to use basic WorldEdit in 1.12 (given the permission fawe.permpack.basic) no longer have the ability to use WorldEdit.

Does the permission fawe.permpack.basic still exist in the latest version? It's still in the plugin.yml file but doesn't appear to be working.

My permission setup has not changed since 1.12. All other permissions (including other FAWE permissions) work correctly, however default users with the permission fawe.permpack.basic cannot use the plugin and get messages such as "You are lacking the permission node: worldedit.wand", which is a permission included in the permpack.

I can provide any additional information about my setup if you need it. 

**How to replicate**:

1. Give a non-op group or user the fawe.permpack.basic permission.
2. Attempt to use WorldEdit

**Checklist**:

- [X] I included a `/fawe debugpaste` link (attempted to do so, no output)
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE (18.11.21)
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by krivoru4k0** [comment] 2019-04-22 03:59
+

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:11
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:11 UTC
