### ISSUE TITLE
Command Blocks 1.13.1

### ISSUE THREAD

**Issue by VoxFoxMC** [boy0001/FastAsyncWorldedit#1141] opened 2018-09-24 04:02 UTC
Copying and pasting command_blocks does not also copy and paste their data.
Tested with build 2049.

**Comment by HauserGrim** [comment] 2018-09-29 17:10
Block inventories are also cleared.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:08
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:08 UTC
Labels: 1.13.X
