### ISSUE TITLE
CRAFTSCRIPTS NOT WORKING ANYMORE IN 1.13

### ISSUE THREAD

**Issue by bidule995** [boy0001/FastAsyncWorldedit#1231] opened 2018-12-19 16:27 UTC
# Bug report

**Debug paste link**:
https://hastebin.com/omefonasos

**Description of the problem:**
The title says everything. Craftscripts are not working anymore in 1.13.2 (and 1.13 too I suppose). This is a severe issue which needs to be fixed as soon as possible.

**How to replicate**:
Try to use a craftscript. (/cs build from build commands doesn't work for example.)

**Checklist**:
- [x] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of FAWE
- [X] I Made sure the bug/error is not caused by any other plugin

![image](https://user-images.githubusercontent.com/16438002/50233156-19e55500-03b3-11e9-9555-cb0d355f37e2.png)

**Comment by braceyourself07** [comment] 2018-12-19 18:48
You using a tool item in hand?

**Comment by bidule995** [comment] 2018-12-20 15:23
> You using a tool item in hand?

Yep, I did.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:11
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:11 UTC
