### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#244] opened 2016-08-18 12:42 UTC
```
Player issued server command: //drain 100
[14:37:49 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:269) [FastAsyncWorldEdit-bukkit18.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalStateException: Asynchronous entity world add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.World.b(World.java:2737) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:904) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:121) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:144) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:591) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.Location.getBlock(Location.java:87) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3.getBlock(Spigot_v1_8_R3.java:209) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:405) ~[?:?]
        at com.sk89q.worldedit.function.mask.BlockMask.test(BlockMask.java:97) ~[?:?]
        at com.sk89q.worldedit.function.mask.MaskIntersection.test(MaskIntersection.java:97) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RecursiveVisitor.isVisitable(RecursiveVisitor.java:52) ~[?:?]
        at com.sk89q.worldedit.function.visitor.BreadthFirstSearch.visit(BreadthFirstSearch.java:141) ~[?:?]
        at com.sk89q.worldedit.function.visitor.BreadthFirstSearch.resume(BreadthFirstSearch.java:175) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:67) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeSmart(Operations.java:75) ~[?:?]
        at com.sk89q.worldedit.EditSession.drainArea(EditSession.java:1731) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommands.drain(UtilityCommands.java:153) ~[?:?]
        ... 12 more
>
```

```
>ver
[14:38:53 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[14:38:53 INFO]: Checking version, please wait...
[14:38:55 INFO]: You are running the latest version
>ver FastAsyncWorldEdit
[14:38:55 INFO]: FastAsyncWorldEdit version 16.08.16-aeb1396-215
[14:38:55 INFO]: Fast Async WorldEdit plugin
[14:38:55 INFO]: Author: Empire92
```

**Comment by L4BORG** [comment] 2016-08-18 12:43
Config: http://pastebin.com/QRTdMWv6

**Comment by L4BORG** [comment] 2016-08-18 12:51
Another one...

```
Player issued server command: //paste
[14:49:35 ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:228) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:269) [FastAsyncWorldEdit-bukkit18.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
        at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.forEach(DiskOptimizedClipboard.java:256) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.place(ClipboardCommands.java:343) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:281) ~[?:?]
        ... 12 more
```

**Comment by HiGuiz1** [comment] 2016-09-12 22:59
Aaaand another one there:
--------------------
Spigot 1.10.2
FAWE configfile: standart
WE configfile: standart, !No changes!
--------------------
`[01:44:31] [Server thread/INFO]: HiGuiz1 issued server command: //smooth
[01:44:45] [Server thread/INFO]: HiGuiz1 issued server command: /help voxelsniper
[01:44:57] [Server thread/INFO]: HiGuiz1 issued server command: //pos1
[01:45:16] [Server thread/INFO]: HiGuiz1 issued server command: //pos2
[01:45:23] [Server thread/INFO]: HiGuiz1 issued server command: //smooth
[01:45:23] [Craft Scheduler Thread - 0/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.3.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.3.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:287) [FastAsyncWorldEdit-bukkit110-16.09.08-741d5ff-281.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
	at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getCachedSection(BukkitQueue_1_10.java:215) ~[?:?]
	at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getCachedSection(BukkitQueue_1_10.java:75) ~[?:?]
	at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:538) ~[?:?]
	at com.boydti.fawe.object.FaweQueue.getCombinedId4Data(FaweQueue.java:296) ~[?:?]
	at com.boydti.fawe.object.extent.FastWorldEditExtent.getLazyBlock(FastWorldEditExtent.java:80) ~[?:?]
	at com.boydti.fawe.object.HistoryExtent.getLazyBlock(HistoryExtent.java:93) ~[?:?]
	at com.sk89q.worldedit.EditSession.getLazyBlock(EditSession.java:712) ~[?:?]
	at com.sk89q.worldedit.EditSession.getHighestTerrainBlock(EditSession.java:796) ~[?:?]
	at com.sk89q.worldedit.math.convolution.HeightMap.<init>(HeightMap.java:81) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommands.smooth(RegionCommands.java:353) ~[?:?]
	... 12 more`

**Comment by HiGuiz1** [comment] 2016-09-14 00:48
Offtop: 
OMG ITS really weird bug(
If you \wands\ your region on Y: -1, -2 or lower, you have THAT BUG(

**Comment by boy0001** [comment] 2016-09-14 01:09
@HiGuiz1 
Try updating FAWE

**Comment by HiGuiz1** [comment] 2016-09-14 02:15
@boy0001 
Im update FAWE plugin on latest version (16.09.11-3a8d54b-284)
RESULT:
<code> 
[05:05:20] [Server thread/INFO]: HiGuiz1 issued server command: //pos1
[05:05:36] [Server thread/INFO]: HiGuiz1 issued server command: //pos2
[05:05:43] [Server thread/INFO]: HiGuiz1 issued server command: //smooth
[05:05:44] [Craft Scheduler Thread - 2/ERROR]: [WorldEdit] An unexpected error while handling a WorldEdit command
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:243) ~[worldedit-bukkit-6.1.3.jar:?]
	at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.3.jar:?]
	at com.sk89q.worldedit.extension.platform.CommandManager$1.run(CommandManager.java:287) [FastAsyncWorldEdit-bukkit110-16.09.11-3a8d54b-284.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.10.2.jar:git-Spigot-f9671b8-48b88ed]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getCachedSection(BukkitQueue_1_10.java:215) ~[?:?]
	at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getCachedSection(BukkitQueue_1_10.java:75) ~[?:?]
	at com.boydti.fawe.example.MappedFaweQueue.getCombinedId4Data(MappedFaweQueue.java:543) ~[?:?]
	at com.boydti.fawe.object.FaweQueue.getCombinedId4Data(FaweQueue.java:296) ~[?:?]
	at com.boydti.fawe.object.extent.FastWorldEditExtent.getLazyBlock(FastWorldEditExtent.java:80) ~[?:?]
	at com.boydti.fawe.object.HistoryExtent.getLazyBlock(HistoryExtent.java:93) ~[?:?]
	at com.sk89q.worldedit.EditSession.getLazyBlock(EditSession.java:712) ~[?:?]
	at com.sk89q.worldedit.EditSession.getHighestTerrainBlock(EditSession.java:796) ~[?:?]
	at com.sk89q.worldedit.math.convolution.HeightMap.<init>(HeightMap.java:81) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommands.smooth(RegionCommands.java:353) ~[?:?]
	... 12 more
[05:05:59] [Server thread/INFO]: HiGuiz1 issued server command: /stop

</code>

**Comment by boy0001** [comment] 2016-09-24 02:44
Smooth should be fixed (with selections that extend outside 0-255)

**Closed by boy0001** 2016-09-24 02:44 UTC
Labels: [!] Bug
