### ISSUE TITLE
Suggestion and/or Bug: Fix door rotation when copy and pasted

### ISSUE THREAD

**Issue by vtesterlwg** [boy0001/FastAsyncWorldedit#1295] opened 2019-04-29 12:23 UTC
When one places a bunch of doors, //copy, //rotate 90, //paste, the doors aren't oriented relatively in the same position. This is annoying when building large symmetric builds.

**Comment by vtesterlwg** [comment] 2019-04-29 23:25
explanatory image:
![q](https://user-images.githubusercontent.com/18277336/56933135-68120f80-6a9b-11e9-89ee-6711375a0aa0.png)

If you copy the top two doors and //rotate 90 and //paste, you get the right two doors, which aren't a great rotation.

**Comment by vtesterlwg** [comment] 2019-04-29 23:26
One has the same issue with //flip - it doesn't flip the door orientation itself as one might like

**Comment by vtesterlwg** [comment] 2019-05-14 17:57
I'm trying to fix this myself but have no clue how, could anyone point me to the part of the code that changes door item meta (for the part of rotation it does correctly) based on the transform rotation?

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:14
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:14 UTC
