### ISSUE TITLE
//replace not working properly

### ISSUE THREAD

**Issue by Gixr** [boy0001/FastAsyncWorldedit#1296] opened 2019-05-04 14:52 UTC
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:

Send command: fawe debugpaste
fawe debugpaste
[16:49:25 INFO]: (FAWE) There was an error handling a FAWE command: [See console]
[16:49:25 INFO]: java.lang.IllegalStateException: Server returned status: 404 Not Found
[16:49:25 ERROR]: An unexpected error occurred while handling a FAWE command
java.lang.IllegalStateException: Server returned status: 404 Not Found
at com.boydti.fawe.util.IncendoPaster.upload(IncendoPaster.java:132) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.boydti.fawe.util.IncendoPaster.debugPaste(IncendoPaster.java:233) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.command.WorldEditCommands.debugpaste(WorldEditCommands.java:117) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at com.sk89q.worldedit.util.command.parametric.ParametricCallable.call(ParametricCallable.java:266) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:134) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.lambda$handleCommandOnCurrentThread$0(CommandManager.java:459) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:481) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:461) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.lambda$null$1(CommandManager.java:575) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.boydti.fawe.object.FawePlayer.lambda$runAction$4(FawePlayer.java:309) ~[FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25) [FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15) [FastAsyncWorldEdit-bukkit-1.13.105%20(2).jar:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [craftbukkit.jar:git-Spigot-518206a-a5b9c7b]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit.jar:git-Spigot-518206a-a5b9c7b]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Description of the problem:**

When i try to replace trees with air to remove them it only removes a few leaves and not all. the easiest way to understand is watch this video: 
https://www.youtube.com/watch?v=2iA7d8YNYAU
**How to replicate**:

just go to a mixed forest and make a large selection then type //replace 18 0 u will see that all the oak leaves will get removed but if you got some birch trees in the forest try //replace 18:2 0 or //Replace birch_leaves 0 and it will just remove a few one 

**Checklist**:

- [x] I made sure that I'm using FAWE on 1.12.2 or lower
- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment] 2019-10-06 03:01
With "//replace minecraft:birch_leaves 0" it works. If you use e.g. 18:2 than FAWE replace only all birch_leaves with **distance 0**.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:14
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:14 UTC
Labels: [?] Testing Required
