### ISSUE TITLE
Error on 1.8.9 Using Java 8

### ISSUE THREAD

**Issue by TheIntelloBox** [boy0001/FastAsyncWorldedit#102] opened 2016-05-08 08:45 UTC
[10:41:52] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to FastAsyncWorldEdit v3.4.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at com.boydti.fawe.object.FawePlayer.getSession(FawePlayer.java:261) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.<init>(FawePlayer.java:90) ~[?:?]
	at com.boydti.fawe.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:15) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.wrap(FaweBukkit.java:113) ~[?:?]
	at com.boydti.fawe.object.FawePlayer.wrap(FawePlayer.java:84) ~[?:?]
	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:309) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor619.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.9.jar:git-Spigot-db6de12-07c3001]
	... 12 more

**Comment by boy0001** [comment] 2016-05-10 04:54
Assuming duplicate of #103

**Closed by boy0001** 2016-05-10 04:54 UTC
