### ISSUE TITLE
Pasting a schematic, and getting where it has been placed (as a region)

### ISSUE THREAD

**Issue by knightzmc** [boy0001/FastAsyncWorldedit#1318] opened 2019-07-04 21:24 UTC
Hey all
I'm trying to use FAWE's API to paste a schematic, and then find the region that it has been pasted into, as I need to then scan the pasted schematic and find the locations of all of a certain block type. However, when looking at the returned EditSession the getMinimumPoint and getMaximumPoint seem to return the edges of the world, meaning the iteration will take massive amounts of time. I've tried different pasting methods, but no method has given an accurate representation of the pasted region. 

Here's what I've tried so far:

```java
    EditSession paste = paste(center, level);
        Region r = new CuboidRegion((World) new BukkitWorld(CELLS_WORLD), paste.getRegionExtent().getMinimumPoint(), paste.getMaximumPoint());
        final Location[] beaconLoc = new Location[1], spawnLoc = new Location[1];
        new TaskBuilder()
                .syncWhenFree(new TaskBuilder.SplitTask() {
                    @Override
                    public Object exec(Object previous) {
                        FastIterator vectors = new FastIterator(r, paste);
                        for (Vector pt : vectors) {
                            int type = r.getWorld().getLazyBlock(pt).getType();
                            if (beaconLoc[0] == null && type == BEACON.getId()) {
                                beaconLoc[0] = Util.vectorToLoc(pt, CELLS_WORLD);
                            }
                            if (spawnLoc[0] == null && type == ENDER_PORTAL_FRAME.getId()) {
                                spawnLoc[0] = Util.vectorToLoc(pt, CELLS_WORLD);
                            }
                        }
                        return null;
                    }
                }).abortIfTrue(previousResult -> (spawnLoc[0] != null && beaconLoc[0] != null)).build();
```

However as mentioned this iterates through all of the blocks in the world, causing hefty lag and not what I'm intending to do.
Is there a way to find the placed region? (I'm using Schematic#paste that returns EditSession to paste it)

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:16
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:16 UTC
