### ISSUE TITLE
Signs and playerheads disappearing

### ISSUE THREAD

**Issue by Thymue** [boy0001/FastAsyncWorldedit#555] opened 2017-05-28 19:48 UTC
**Debug paste link**:https://hastebin.com/pasayutaka

**Description of the problem:**
When i //copy a region which contains head of some player or sign with text and then //paste it head of the player changes to skeleton skull and sign text just disappear..
(they are invisible until you for example left click them with //wand)

**How to replicate**:
1.Place a head of a player and/or a sign with a text
2.Copy head of a player/sign with a text
3.Paste it and you'll see invisible head and/or invisible sign
4.Get a //wand to your hand and use left click to make them not invisible.
**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)]
*there is but it has a tick and it's still not repaired so..
- [X] I made sure I am using an up-to-date version of FAWE
*FAWE 17.5.28 (means the date when i posted this)
- [X] I Made sure the bug/error is not caused by any other plugin
*Tested it on server with only Vault,WE and FAWE.

**Comment by Malfrador** [comment] 2017-05-29 16:46
Dynmap also stops working when it tries to render a chunk with a invisible sign/head/etc. in it. And the sign stays empty, even after breaking/leftclicking it.
`[18:36:50 ERROR]: [dynmap] Exception while fetching chunks:
java.lang.ArrayIndexOutOfBoundsException: 137
        at org.bukkit.craftbukkit.v1_11_R1.CraftChunkSnapshot.getBlockTypeId(CraftChunkSnapshot.java:56) ~[spigot.jar:git-Paper-1058]
        at org.dynmap.bukkit.NewMapChunkCache.loadChunks(NewMapChunkCache.java:836) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:458) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:445) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[spigot.jar:git-Paper-1058]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) ~[spigot.jar:git-Paper-1058]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) ~[spigot.jar:git-Paper-1058]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) ~[spigot.jar:git-Paper-1058]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) ~[spigot.jar:git-Paper-1058]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) ~[spigot.jar:git-Paper-1058]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by Thymue** [comment] 2017-05-29 18:03
idk, but i believe there's a way to fix it
i think this is maybe the last (in my opinion somewhat important) issue that needs to be fixed and then it'll be the best we plugin/add-on

**Comment by Serux18** [comment] 2017-05-29 18:21
I can confirm that this is happening in Spigot 1.11.2

Any sign becomes invisible when copied and the heads are transformed into skeleton heads

**Comment by mibby** [comment] 2017-05-30 23:52
> Dynmap also stops working when it tries to render a chunk with a invisible sign/head/etc

I think I also had this experience happen to me too. A few users came to me to complain that dynmap stopped rendering when they placed blocks down by hand. Server restart seemed to have fixed the issue.

Also could be related, a player said he could place sand down to gain (dupe) mcmmo experience over and over again, but this should be prevented with the mcmmo region files it creates to protect against it.  Server restart resolved the problem as I wasn't able to reproduce after that. So if FAWE is breaking chunk rendering / look-up for other plugins (i.e. dynmap), possible it did the same for mcmmo as well. Server restart

**Comment by mibby** [comment] 2017-06-03 01:43
@boy0001 Possible FAWE is breaking dynmap and mcmmo due to the improved ChunkListener here?
 https://github.com/boy0001/FastAsyncWorldedit/commit/b9c056c879d8b9277801d10d30f6a57209c9d6a2

**Comment by boy0001** [comment] 2017-06-03 09:36
Should be fixed

**Closed by boy0001** 2017-06-03 09:36 UTC
