### ISSUE TITLE
Unable to locate sign at x, y, z

### ISSUE THREAD

**Issue by McPlayHD** [boy0001/FastAsyncWorldedit#1292] opened 2019-04-25 22:41 UTC
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:
https://pastebin.com/t7qVf3XW

**Description of the problem:**
**How to replicate**:
I made a schematic file with the latest versions of FAWE and Spigot 1.8.8 and am now inserting it with my self-written plugin on another server also with the latest versions of FAWE and Spigot 1.8.8.

Here you can see my code-snippet for this task:

`com.sk89q.worldedit.Vector pos = new com.sk89q.worldedit.Vector(x,y,z);`

`EditSession editSession = ClipboardFormats.findByFile(schematicfile).load(schematicfile).paste(FaweAPI.getWorld(WORLDNAME), pos, false, true, null);`

`editSession.flushQueue();`

The schematic is inserted correctly but everytime the player then gets teleported to the location the first thing he sees in his chat is a spam of 

> Unable to locate sign at x, y, z

In the following picture you can see what I mean by this issue

![2019-04-26_00 30 31](https://user-images.githubusercontent.com/7106489/56772726-78846a80-67bb-11e9-94c5-1c61f8ea0e98.png)

There are no Errors in the console and the signs are on the map. I'm using the standard version of Minecraft without any mods.

**Checklist**:

- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:14
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:14 UTC
