### ISSUE TITLE
fixlighting level issues

### ISSUE THREAD

**Issue by aldesrahim** [boy0001/FastAsyncWorldedit#1294] opened 2019-04-27 10:17 UTC
i've worked on large area use worldedit `//set air` , and the area is deep enough, but the light broke and i've use `//fixlighting`, but the light level is broken, this some pictures

![2019-04-27_17 04 17](https://user-images.githubusercontent.com/37100012/56848158-b1355880-690f-11e9-9e4d-424b99c1c701.png)

why the right zombie is burn by sun, because i add some block above it to reload light level, but if i work on very large area, i cant manually place block above it, i tried to use `//set whatever` but still same, then the cave light is broke too. how to fix this ?

**Comment by monkey8113** [comment] 2019-05-07 15:43
i have same issue, none seems to fix it

**Comment by mrcoffee1026** [comment] 2019-05-07 16:38
Don't know if you've tried but when I had glitchy light levels in an area, I'd select that area do //removelighting ... and THEN //fixlighting on the same area... this USED to fix it, does it for you now?

**Comment by monkey8113** [comment] 2019-05-07 20:41
I also discovered that, however if I did fix lighting the area would be super bright again regardless. 
If using removelight, any changes of block on the ceiling would cause it to revert to its bright state. Giving that the ceiling is made with fawe. As if fawe placed glass ceiling disguised as other block. Removing the ceiling and placing the block by hand do fix the light problem. But that's not why I use fawe.

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:14
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:14 UTC
