### ISSUE TITLE
java.lang.NullPointerException: Could not dispatch event to handler

### ISSUE THREAD

**Issue by NLBlacky** [boy0001/FastAsyncWorldedit#1354] opened 2020-02-17 20:34 UTC
**Debug paste link**:
https://athion.net/ISPaster/paste/view/b8b1b53802a4412b9c352758e787c80b

**Description of the problem:**
We decided to add FAWE to 12 of our modpacks. Around half of those modpacks have the following error spammed in console: https://pastebin.com/1KtxqzNb
While the spam is annoying, players reported to be unable to use FAWE. In the beginning someone thought it were the conduits from EnderIO but I have been unable to confirm this yet. Permissions were setup correctly to my knowledge (permissions: https://i.ibb.co/yPYpG11/World-Edit-Permissions.png)

**How to replicate**:
I've tried to replicate the issue with 2 modpacks on a seperate test server. I used the following Sponge versions (spongeforge-1.12.2-2838-7.1.7-RC3924.jar, spongeforge-1.12.2-2838-7.1.9.jar, spongeforge-1.12.2-2838-7.1.7-RC3924.jar and spongeforge-1.12.2-2838-7.1.7-RC3906.jar), tried 2 versions of Forge (FTBserver-1.12.2-14.23.5.2846-universal.jar and forge-1.12.2-14.23.5.2847-universal.jar) and used both the 1.12.2 Forge and 1.12.2 Sponge version of FAWE but was unable to replicate the issue (Forge version crashed with Sponge). All servers run the same Sponge version, most of them run forge-1.12.2-14.23.5.2847-universal.jar, plugins on all servers are the same only the mods are different (while many are common though). 

With the provided information and log I was hoping you might be able to help me to find the cause of this issue. FAWE is way too performance friendly to ignore so we would really like to have it working on all servers.

**Checklist**:
- [X] I read the information at the top of the issue stating that versions up to 1.12 are classified as legacy and receive limited to none support. Given that, I understand that my issue won't receive an answer or fix anytime soon since my version is very old and I should update my server to a newer version of minecraft.
- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:18
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:18 UTC
