### ISSUE TITLE
event.setExtent(new AbstractDelegateExtent(event.getExtent()) not working as expected

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncWorldedit#1190] opened 2018-11-08 10:01 UTC
So using latest FAWE on 1.8.8 server...

here's the example code which works just fine when FAWE is not preset on server...

```
@Subscribe(priority = EventHandler.Priority.VERY_EARLY)
	public void onEditSessionEvent(EditSessionEvent event)
	{
		Bukkit.getLogger().info("EditSessionEvent");
		event.setExtent(new AbstractDelegateExtent(event.getExtent())
		{
			@Override
			public boolean setBlock(Vector location, BaseBlock block) throws WorldEditException
			{
				Bukkit.getLogger().info("id: "+block.getId());
				return super.setBlock(location, block);
			}
		});
	}
```

when FAWE is not present, EditSessionEvent is printed and then id: ... is printed as expected. But as soon as I add FAWE only EditSessionEvent is printed and the code "event.setExtent(new AbstractDelegateExtent(event.getExtent()) { ..." is not executed anymore.

I guess LogBlock logging would also be broken if FAWE is present: https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/worldedit/WorldEditLoggingHook.java They're doing the same thing but with old WE API.

So my question would be... is there any other way I can make this work? 

My goal is to override "public boolean setBlock(Vector location, BaseBlock block) throws WorldEditException"

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of FAWE
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:09
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:09 UTC
