### ISSUE TITLE
Copy/Paste issue due changes on spigot

### ISSUE THREAD

**Issue by TheCalypso** [boy0001/FastAsyncWorldedit#1212] opened 2018-12-08 00:31 UTC
# Bug report

**Debug paste link**:

https://hastebin.com/vodamonapa
https://pastebin.com/geMvNq8Q

**Comment by N0tMyFaultOG** [comment] 2018-12-18 17:59
Duplicate of https://github.com/boy0001/FastAsyncWorldedit/issues/1213

**Closed by N0tMyFaultOG** 2018-12-18 17:59 UTC
