### ISSUE TITLE
Players disappear after setbiome with code

### ISSUE THREAD

**Issue by Xierip** [boy0001/FastAsyncWorldedit#1280] opened 2019-03-23 23:49 UTC
# Bug report for FastAsyncWorldEdit < 1.12.2

**Debug paste link**:
https://incendo.org/paste/view/10d9d2e12ec14b1b8bdd55933f8ecda2

**Description of the problem:**

When setbiome with this code:
`    CuboidRegion cuboidRegion = new CuboidRegion(island.getIslandChunk().getMinWG(), island.getIslandChunk().getMaxWG());
`
`
    FlatRegionFunction replace = new BiomeReplace(
        new EditSessionBuilder(FaweAPI.getWorld(Worlds.NORMAL.getName())).fastmode(true).limitUnlimited().build().getExtent(),
        new BaseBiome(biome.ordinal()));
`
`
    final FlatRegionVisitor visitor = new FlatRegionVisitor(Regions.asFlatRegion(cuboidRegion), replace);
`
`
    try {
      Operations.completeLegacy(visitor);
    } catch (MaxChangedBlocksException e) {
      e.printStackTrace();
    }`
Players in region disappear, and border sended by packets disappear
**How to replicate**:

Use my code

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:13
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:13 UTC
