### ISSUE TITLE
FAWE freezes and doesn't respond to commands or wand (1.12.2)

### ISSUE THREAD

**Issue by Germanode** [boy0001/FastAsyncWorldedit#1320] opened 2019-07-07 17:30 UTC
**Debug paste link**:

Impossible to do. Plugin stopped responding - this command doesn't work too. No console error logged.

**Description of the problem:**

Sometimes, for random reasons, FAWE (latest for 1.12.2) freezes and doesn't respond to commands like /thru, using the wand (any command actually). 
Enough ram, all other plugins work as they should, plugins NOT reloaded.

Using it on latest 1.12.2 paper spigot. This started occurring like a month ago. Every so often.

After FAWE freezes, I am also unable to throw away blocks (they disappear from inventory but don't show up on the ground). At the same exact time, PlaceholderAPI goes to hell as well with some of the placeholders.

**How to replicate**:

Happens absolutely randomly without any notice or warnings.

**Checklist**:
- [X] I made sure that I'm using FAWE on 1.12.2 or lower
- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/boy0001/FastAsyncWorldedit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE < 1.12.2](https://ci.athion.net/job/FastAsyncWorldEdit/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by OfficialCRUGG** [comment] 2019-11-12 13:20
For me, selecting stuff etc. works, but once I try to copy something (when I had /wea disabled it told me to enable it) and had wea enabled, it didn't respond. Since that, it didn't respond to anything else until I rejoined. When I then try to copy, it doesn't work again. Same for setting blocks for example. It tells me that the Operation was queued, but doesn't do anything.

**Comment by SaltyAimbOtter** [comment] 2019-11-13 20:45
This happend to my builders on 1.14 too. They placed blocks using brushes etc. but couldnt see them nor see any command feedback. After some hours all worked fine again and i saw the changed blocks.
Here is my paste:
https://athion.net/ISPaster/paste/view/37a80518af174606b1b68e6557020dda
I maanged to filter this exception out of my spammed log: https://pastebin.com/ejFYqjzQ

**Comment by N0tMyFaultOG** [comment] 2020-05-29 22:16
Your ticket has been closed because it falls into one of the following categories:

- Your issue has been fixed in a newer version of FastAsyncWorldEdit for versions 1.8 - 1.12.2, get the latest build [here](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/target/) matching the platform you need.

- Your issue targets minecraft version 1.13 or higher. This is the wrong repository then. Move to [this repository](https://github.com/IntellectualSites/FastAsyncWorldEdit) and open a bug report here.
BUT BEWARE: You should consider updating to 1.15.2, using the latest Fawe build for 1.15.2 (Build 255 when writing this, get it [here](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)) and reproducing the issue in a clean environment (fresh setup Spigot or Paper server).

- Your issue has been fixed in a build of FAWE for 1.15 or an issue exists on our new repository.

- You either didn't fill out the template or deleted it.

If none of the bullet points suits, head to the second one.

**Closed by N0tMyFaultOG** 2020-05-29 22:16 UTC
